name: action-download-artifacts
description: Download all artifacts from given workflow run
author: CDQ AG

branding:
  icon: download-cloud
  color: green

inputs:
  github-token:
    description: GitHub token
    default: ${{ github.token }}

  run-id:
    description: The ID of the workflow run
    default: ${{ github.run_id }}

  name-pattern:
    description: The artifact name pattern (regexp)
    default: '.*'

  auto-unzip:
    description: Automatically unzip downloaded artifacts
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run download script
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        RUN_ID: ${{ inputs.run-id }}
        # GITHUB_REPOSITORY is available by default
        NAME_PATTERN: ${{ inputs.name-pattern }}
        AUTO_UNZIP: ${{ inputs.auto-unzip }}
      run: ${{ github.action_path }}/download.sh
